const COMMAND_METADATA = [
	{
		id: 'help',
		name: 'help',
		registrationOrder: 1,
		category: 'general',
		permission: 'everyone',
		descriptionKey: 'commands.help.description',
		options: [],
		examples: ['/help'],
		help: {
			order: 10,
			detailsKey: 'commands.help.available',
		},
		guildOnly: true,
		handler: './help',
	},
	{
		id: 'rpg',
		name: 'rpg',
		registrationOrder: 4,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'commands.rpg.description',
		options: [],
		examples: ['/rpg help'],
		help: {
			order: 30,
			detailsKey: 'rpg.help.body',
		},
		guildOnly: true,
		group: true,
	},
	{
		id: 'say',
		name: 'say',
		registrationOrder: 5,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.say.description',
		options: [
			{
				name: 'message',
				type: 'string',
				descriptionKey: 'commands.say.message',
				required: true,
				maxLength: 2_000,
			},
		],
		examples: ['/say message:<text>'],
		help: { order: 50 },
		guildOnly: true,
		handler: './say',
	},
	{
		id: 'purge',
		name: 'purge',
		registrationOrder: 2,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.purge.description',
		options: [
			{
				name: 'amount',
				type: 'integer',
				descriptionKey: 'commands.purge.amount',
				required: true,
				minValue: 2,
				maxValue: 100,
				autocomplete: {
					provider: 'static',
					values: [2, 5, 10, 25, 50, 100],
				},
			},
		],
		examples: ['/purge amount:<2-100>'],
		help: { order: 60 },
		guildOnly: true,
		handler: './purge',
	},
	{
		id: 'restart',
		name: 'restart',
		registrationOrder: 3,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.restart.description',
		options: [],
		examples: ['/restart'],
		help: { order: 70 },
		guildOnly: true,
		handler: './restart',
	},
	{
		id: 'rpg:gen',
		parent: 'rpg',
		name: 'gen',
		registrationOrder: 7,
		category: 'rpg',
		permission: 'dm',
		descriptionKey: 'rpg.gen.schemaDescription',
		options: [
			{
				name: 'category',
				type: 'string',
				descriptionKey: 'rpg.gen.categoryOption',
				required: true,
				autocomplete: { provider: 'generator-categories' },
			},
		],
		examples: ['/rpg gen category:<category>'],
		help: {
			order: 10,
			summaryKey: 'rpg.gen.description',
		},
		guildOnly: true,
		handler: './rpg/subcommands/gen',
	},
	{
		id: 'rpg:gen-char',
		parent: 'rpg',
		name: 'gen-char',
		registrationOrder: 8,
		category: 'rpg',
		permission: 'dm',
		descriptionKey: 'rpg.genChar.schemaDescription',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.genChar.keyOption',
				required: true,
				minLength: 1,
				maxLength: 50,
			},
			{
				name: 'level',
				type: 'integer',
				descriptionKey: 'rpg.genChar.levelOption',
				minValue: 1,
				maxValue: 10,
				autocomplete: {
					provider: 'static',
					values: Array.from({ length: 10 }, (_, index) => ({
						value: index + 1,
						nameKey: 'rpg.genChar.levelChoice',
						nameVariables: { level: index + 1 },
					})),
				},
			},
			{
				name: 'background',
				type: 'string',
				descriptionKey: 'rpg.genChar.backgroundOption',
				autocomplete: { provider: 'backgrounds' },
			},
		],
		examples: ['/rpg gen-char character-key:<new key> [level] [background]'],
		help: {
			order: 11,
			summaryKey: 'rpg.genChar.description',
		},
		guildOnly: true,
		handler: './rpg/subcommands/genchar',
	},
	{
		id: 'rpg:gen-help',
		parent: 'rpg',
		name: 'gen-help',
		registrationOrder: 9,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.genHelp.schemaDescription',
		options: [],
		examples: ['/rpg gen-help'],
		help: {
			order: 12,
			summaryKey: 'rpg.genHelp.description',
			detailsKey: 'rpg.genHelp.body',
		},
		guildOnly: true,
		handler: './rpg/subcommands/genhelp',
	},
	{
		id: 'rpg:roll',
		parent: 'rpg',
		name: 'roll',
		registrationOrder: 12,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.roll.description',
		options: [
			{
				name: 'expression',
				type: 'string',
				descriptionKey: 'rpg.roll.expressionOption',
				required: true,
				autocomplete: {
					provider: 'static',
					values: [
						'1d4',
						'1d6',
						'2d6',
						'1d8',
						'2d8',
						'1d10',
						'1d12',
						'1d20',
						'1d100',
						'4d6',
					],
				},
			},
		],
		examples: [
			'/rpg roll expression:1d20',
			'/rpg roll expression:2d6+3',
		],
		help: { order: 15 },
		guildOnly: true,
		handler: './rpg/subcommands/roll',
	},
	{
		id: 'rpg:add',
		parent: 'rpg',
		name: 'add',
		registrationOrder: 1,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.add.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.add.keyOption',
				required: true,
				minLength: 1,
				maxLength: 50,
			},
		],
		examples: ['/rpg add character-key:<new key>'],
		help: { order: 20 },
		guildOnly: true,
		handler: './rpg/subcommands/add',
	},
	{
		id: 'rpg:get',
		parent: 'rpg',
		name: 'get',
		registrationOrder: 14,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.get.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.get.characterOption',
				required: true,
				autocomplete: { provider: 'characters' },
			},
			{
				name: 'field',
				type: 'string',
				descriptionKey: 'rpg.get.fieldOption',
				autocomplete: { provider: 'viewable-fields' },
			},
		],
		examples: [
			'/rpg get character-key:<key>',
			'/rpg get character-key:<key> field:<field>',
		],
		help: { order: 30 },
		guildOnly: true,
		handler: './rpg/subcommands/get',
	},
	{
		id: 'rpg:get-help',
		parent: 'rpg',
		name: 'get-help',
		registrationOrder: 15,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.getHelp.description',
		options: [],
		examples: ['/rpg get-help'],
		help: {
			order: 35,
			detailsKey: 'rpg.getHelp.body',
		},
		guildOnly: true,
		handler: './rpg/subcommands/gethelp',
	},
	{
		id: 'rpg:set',
		parent: 'rpg',
		name: 'set',
		registrationOrder: 4,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.set.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.set.characterOption',
				required: true,
				autocomplete: { provider: 'characters' },
			},
			{
				name: 'field',
				type: 'string',
				descriptionKey: 'rpg.set.fieldOption',
				required: true,
				autocomplete: { provider: 'editable-fields' },
			},
		],
		examples: ['/rpg set character-key:<key> field:<field>'],
		help: { order: 40 },
		guildOnly: true,
		handler: './rpg/subcommands/set',
	},
	{
		id: 'rpg:set-help',
		parent: 'rpg',
		name: 'set-help',
		registrationOrder: 5,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.setHelp.description',
		options: [],
		examples: ['/rpg set-help'],
		help: {
			order: 45,
			detailsKey: 'rpg.setHelp.body',
		},
		guildOnly: true,
		handler: './rpg/subcommands/sethelp',
	},
	{
		id: 'rpg:heal',
		parent: 'rpg',
		name: 'heal',
		registrationOrder: 11,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.heal.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.heal.characterOption',
				required: true,
				autocomplete: { provider: 'characters' },
			},
			{
				name: 'resource',
				type: 'string',
				descriptionKey: 'rpg.heal.resourceOption',
				required: true,
				choices: [
					{ nameKey: 'rpg.heal.hpChoice', value: 'hp' },
					{ nameKey: 'rpg.heal.armorChoice', value: 'armor' },
					{ nameKey: 'rpg.heal.bothChoice', value: 'both' },
				],
			},
			{
				name: 'percentage',
				type: 'number',
				descriptionKey: 'rpg.heal.percentageOption',
				required: true,
				minValue: 0,
				maxValue: 100,
				autocomplete: {
					provider: 'static',
					values: [0, 25, 50, 75, 100].map(value => ({
						name: `${value}%`,
						value,
					})),
				},
			},
		],
		examples: [
			'/rpg heal character-key:<key> resource:<hp|armor|both> percentage:<0-100>',
		],
		help: { order: 50 },
		guildOnly: true,
		handler: './rpg/subcommands/heal',
	},
	{
		id: 'rpg:damage',
		parent: 'rpg',
		name: 'damage',
		registrationOrder: 2,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.damage.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.damage.characterOption',
				required: true,
				autocomplete: { provider: 'characters' },
			},
			{
				name: 'damage-amount',
				type: 'integer',
				descriptionKey: 'rpg.damage.amountOption',
				required: true,
				minValue: 1,
				autocomplete: {
					provider: 'static',
					values: [1, 5, 10, 15, 20, 25, 50, 100].map(value => ({
						value,
						nameKey: 'rpg.damage.choice',
						nameVariables: { amount: value },
					})),
				},
			},
			{
				name: 'piercing',
				type: 'boolean',
				descriptionKey: 'rpg.damage.piercingOption',
			},
		],
		examples: [
			'/rpg damage character-key:<key> damage-amount:<number> [piercing]',
		],
		help: { order: 55 },
		guildOnly: true,
		handler: './rpg/subcommands/damage',
	},
	{
		id: 'rpg:end-turn',
		parent: 'rpg',
		name: 'end-turn',
		registrationOrder: 6,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.endTurn.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.endTurn.characterOption',
				required: true,
				autocomplete: { provider: 'characters' },
			},
		],
		examples: ['/rpg end-turn character-key:<key>'],
		help: { order: 60 },
		guildOnly: true,
		handler: './rpg/subcommands/endturn',
	},
	{
		id: 'rpg:delete',
		parent: 'rpg',
		name: 'delete',
		registrationOrder: 3,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.delete.description',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.delete.characterOption',
				required: true,
				autocomplete: { provider: 'manageable-characters' },
			},
		],
		examples: ['/rpg delete character-key:<key>'],
		help: { order: 70 },
		guildOnly: true,
		handler: './rpg/subcommands/delete',
	},
	{
		id: 'rpg:rules',
		parent: 'rpg',
		name: 'rules',
		registrationOrder: 13,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.rules.description',
		options: [],
		examples: ['/rpg rules'],
		help: { order: 80 },
		guildOnly: true,
		handler: './rpg/subcommands/rules',
	},
	{
		id: 'rpg:help',
		parent: 'rpg',
		name: 'help',
		registrationOrder: 10,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.help.description',
		options: [],
		examples: ['/rpg help'],
		help: {
			order: 90,
			detailsKey: 'rpg.help.body',
		},
		guildOnly: true,
		handler: './rpg/subcommands/help',
	},
];

module.exports = { COMMAND_METADATA };