const COMMAND_METADATA = [
	{
		id: 'help',
		name: 'help',
		registrationOrder: 1,
		category: 'general',
		permission: 'everyone',
		descriptionKey: 'commands.help.description',
		options: [
			{
				name: 'command',
				type: 'string',
				descriptionKey: 'commands.help.commandOption',
				acceptedValuesKey: 'commands.help.commandAccepted',
				autocomplete: { provider: 'help-commands' },
			},
		],
		examples: ['/help', '/help command:<command>'],
		help: {
			order: 10,
			detailsKey: 'commands.help.behavior',
		},
		guildOnly: true,
		handler: './handlers/help',
	},
	{
		id: 'say',
		name: 'say',
		registrationOrder: 15,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.say.description',
		options: [
			{
				name: 'message',
				type: 'string',
				descriptionKey: 'commands.say.message',
				required: true,
				maxLength: 2_000,
			},
		],
		examples: ['/say message:<text>'],
		help: {
			order: 100,
			detailsKey: 'commands.say.behavior',
		},
		guildOnly: true,
		handler: './handlers/say',
	},
	{
		id: 'purge',
		name: 'purge',
		registrationOrder: 2,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.purge.description',
		options: [
			{
				name: 'amount',
				type: 'integer',
				descriptionKey: 'commands.purge.amount',
				required: true,
				minValue: 2,
				maxValue: 100,
				autocomplete: {
					provider: 'static',
					values: [2, 5, 10, 25, 50, 100],
				},
			},
		],
		examples: ['/purge amount:<2-100>'],
		help: {
			order: 110,
			detailsKey: 'commands.purge.behavior',
		},
		guildOnly: true,
		handler: './handlers/purge',
	},
	{
		id: 'reload',
		name: 'reload',
		registrationOrder: 3,
		category: 'moderation',
		permission: 'moderator',
		descriptionKey: 'commands.reload.description',
		options: [],
		examples: ['/reload'],
		help: {
			order: 120,
			detailsKey: 'commands.reload.behavior',
		},
		guildOnly: true,
		handler: './handlers/reload',
	},
	{
		id: 'gen',
		name: 'gen',
		registrationOrder: 9,
		category: 'rpg',
		permission: 'dm',
		descriptionKey: 'rpg.gen.schemaDescription',
		options: [
			{
				name: 'category',
				type: 'string',
				descriptionKey: 'rpg.gen.categoryOption',
				required: true,
				autocomplete: {
					provider: 'generator-categories',
					showAllInHelp: true,
				},
			},
		],
		examples: ['/gen category:<category>'],
		help: {
			order: 20,
			summaryKey: 'rpg.gen.description',
			detailsKey: 'rpg.gen.behavior',
		},
		guildOnly: true,
		handler: './handlers/gen',
	},
	{
		id: 'gen-char',
		name: 'gen-char',
		registrationOrder: 10,
		category: 'rpg',
		permission: 'dm',
		descriptionKey: 'rpg.genChar.schemaDescription',
		options: [
			{
				name: 'character-key',
				type: 'string',
				descriptionKey: 'rpg.genChar.keyOption',
				required: true,
				minLength: 1,
				maxLength: 50,
			},
			{
				name: 'level',
				type: 'integer',
				descriptionKey: 'rpg.genChar.levelOption',
				minValue: 1,
				maxValue: 10,
				autocomplete: {
					provider: 'static',
					values: Array.from({ length: 10 }, (_, index) => ({
						value: index + 1,
						nameKey: 'rpg.genChar.levelChoice',
						nameVariables: { level: index + 1 },
					})),
				},
			},
			{
				name: 'background',
				type: 'string',
				descriptionKey: 'rpg.genChar.backgroundOption',
				autocomplete: { provider: 'backgrounds' },
			},
		],
		examples: ['/gen-char character-key:<new key> [level] [background]'],
		help: {
			order: 21,
			summaryKey: 'rpg.genChar.description',
			detailsKey: 'rpg.genChar.behavior',
		},
		guildOnly: true,
		handler: './handlers/genChar',
	},
	{
		id: 'gen-monster',
		name: 'gen-monster',
		registrationOrder: 11,
		category: 'rpg',
		permission: 'dm',
		descriptionKey: 'rpg.genMonster.schemaDescription',
		options: [
			{
				name: 'creature-key',
				type: 'string',
				descriptionKey: 'rpg.genMonster.keyOption',
				required: true,
				minLength: 1,
				maxLength: 50,
			},
			{
				name: 'type',
				type: 'string',
				descriptionKey: 'rpg.genMonster.typeOption',
				required: true,
				choices: [
					{ nameKey: 'rpg.genMonster.monsterChoice', value: 'monster' },
					{ nameKey: 'rpg.genMonster.animalChoice', value: 'animal' },
					{ nameKey: 'rpg.genMonster.companionChoice', value: 'companion' },
				],
			},
			{
				name: 'level',
				type: 'integer',
				descriptionKey: 'rpg.genMonster.levelOption',
				minValue: 1,
				maxValue: 10,
				autocomplete: {
					provider: 'static',
					values: Array.from({ length: 10 }, (_, index) => ({
						value: index + 1,
						nameKey: 'rpg.genMonster.levelChoice',
						nameVariables: { level: index + 1 },
					})),
				},
			},
		],
		examples: [
			'/gen-monster creature-key:<new key> type:<monster|animal|companion>',
			'/gen-monster creature-key:<new key> type:<type> level:<1-10>',
		],
		help: {
			order: 22,
			summaryKey: 'rpg.genMonster.description',
			detailsKey: 'rpg.genMonster.behavior',
		},
		guildOnly: true,
		handler: './handlers/genMonster',
	},
	{
		id: 'roll',
		name: 'roll',
		registrationOrder: 12,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.roll.description',
		options: [
			{
				name: 'expression',
				type: 'string',
				descriptionKey: 'rpg.roll.expressionOption',
				acceptedValuesKey: 'rpg.roll.acceptedValues',
				required: true,
				autocomplete: {
					provider: 'static',
					values: [
						'1d4',
						'1d6',
						'2d6',
						'1d8',
						'2d8',
						'1d10',
						'1d12',
						'1d20',
						'1d100',
						'4d6',
					],
				},
			},
		],
		examples: [
			'/roll expression:1d20',
			'/roll expression:2d6+3',
		],
		help: {
			order: 25,
			detailsKey: 'rpg.roll.behavior',
		},
		guildOnly: true,
		handler: './handlers/roll',
	},
	{
		id: 'add',
		name: 'add',
		registrationOrder: 4,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.add.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.add.keyOption',
				required: true,
				minLength: 1,
				maxLength: 50,
			},
			{
				name: 'type',
				type: 'string',
				descriptionKey: 'rpg.add.typeOption',
				choices: [
					{ nameKey: 'entity.types.character', value: 'character' },
					{ nameKey: 'entity.types.creature', value: 'creature' },
				],
			},
		],
		examples: [
			'/add entity-key:<new key>',
			'/add entity-key:<new key> type:<creature>',
		],
		help: {
			order: 30,
			detailsKey: 'rpg.add.behavior',
		},
		guildOnly: true,
		handler: './handlers/add',
	},
	{
		id: 'get',
		name: 'get',
		registrationOrder: 14,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.get.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.get.entityOption',
				required: true,
				autocomplete: { provider: 'entities' },
			},
			{
				name: 'field',
				type: 'string',
				descriptionKey: 'rpg.get.fieldOption',
				autocomplete: {
					provider: 'entity-sections',
					showAllInHelp: true,
				},
			},
		],
		examples: [
			'/get entity-key:<key>',
			'/get entity-key:<key> field:<field>',
		],
		help: {
			order: 40,
			detailsKey: 'rpg.get.behavior',
		},
		guildOnly: true,
		handler: './handlers/get',
	},
	{
		id: 'set',
		name: 'set',
		registrationOrder: 7,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.set.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.set.entityOption',
				required: true,
				autocomplete: { provider: 'entities' },
			},
			{
				name: 'field',
				type: 'string',
				descriptionKey: 'rpg.set.fieldOption',
				required: true,
				autocomplete: {
					provider: 'entity-sections',
					showAllInHelp: true,
				},
			},
		],
		examples: ['/set entity-key:<key> field:<field>'],
		help: {
			order: 50,
			detailsKey: 'rpg.set.behavior',
		},
		guildOnly: true,
		handler: './handlers/set',
	},
	{
		id: 'heal',
		name: 'heal',
		registrationOrder: 11,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.heal.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.heal.entityOption',
				required: true,
				autocomplete: { provider: 'entities' },
			},
			{
				name: 'resource',
				type: 'string',
				descriptionKey: 'rpg.heal.resourceOption',
				required: true,
				choices: [
					{ nameKey: 'rpg.heal.hpChoice', value: 'hp' },
					{ nameKey: 'rpg.heal.armorChoice', value: 'armor' },
					{ nameKey: 'rpg.heal.bothChoice', value: 'both' },
				],
			},
			{
				name: 'percentage',
				type: 'number',
				descriptionKey: 'rpg.heal.percentageOption',
				required: true,
				minValue: 0,
				maxValue: 100,
				autocomplete: {
					provider: 'static',
					values: [0, 25, 50, 75, 100].map(value => ({
						name: `${value}%`,
						value,
					})),
				},
			},
		],
		examples: [
			'/heal entity-key:<key> resource:<hp|armor|both> percentage:<0-100>',
		],
		help: {
			order: 60,
			detailsKey: 'rpg.heal.behavior',
		},
		guildOnly: true,
		handler: './handlers/heal',
	},
	{
		id: 'damage',
		name: 'damage',
		registrationOrder: 5,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.damage.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.damage.entityOption',
				required: true,
				autocomplete: { provider: 'entities' },
			},
			{
				name: 'damage-amount',
				type: 'integer',
				descriptionKey: 'rpg.damage.amountOption',
				required: true,
				minValue: 1,
				autocomplete: {
					provider: 'static',
					values: [1, 5, 10, 15, 20, 25, 50, 100].map(value => ({
						value,
						nameKey: 'rpg.damage.choice',
						nameVariables: { amount: value },
					})),
				},
			},
			{
				name: 'piercing',
				type: 'boolean',
				descriptionKey: 'rpg.damage.piercingOption',
			},
		],
		examples: [
			'/damage entity-key:<key> damage-amount:<number> [piercing]',
		],
		help: {
			order: 65,
			detailsKey: 'rpg.damage.behavior',
		},
		guildOnly: true,
		handler: './handlers/damage',
	},
	{
		id: 'end-turn',
		name: 'end-turn',
		registrationOrder: 8,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.endTurn.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.endTurn.entityOption',
				required: true,
				autocomplete: { provider: 'entities' },
			},
		],
		examples: ['/end-turn entity-key:<key>'],
		help: {
			order: 70,
			detailsKey: 'rpg.endTurn.behavior',
		},
		guildOnly: true,
		handler: './handlers/endTurn',
	},
	{
		id: 'delete',
		name: 'delete',
		registrationOrder: 6,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.delete.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.delete.entityOption',
				required: true,
				autocomplete: { provider: 'manageable-entities' },
			},
		],
		examples: ['/delete entity-key:<key>'],
		help: {
			order: 80,
			detailsKey: 'rpg.delete.behavior',
		},
		guildOnly: true,
		handler: './handlers/delete',
	},
	{
		id: 'undo',
		name: 'undo',
		registrationOrder: 15,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.undo.description',
		options: [
			{
				name: 'entity-key',
				type: 'string',
				descriptionKey: 'rpg.undo.entityOption',
				required: true,
				autocomplete: { provider: 'undoable-entities' },
			},
		],
		examples: ['/undo entity-key:<key>'],
		help: {
			order: 75,
			detailsKey: 'rpg.undo.behavior',
		},
		guildOnly: true,
		handler: './handlers/undo',
	},
	{
		id: 'rules',
		name: 'rules',
		registrationOrder: 13,
		category: 'rpg',
		permission: 'everyone',
		descriptionKey: 'rpg.rules.description',
		options: [],
		examples: ['/rules'],
		help: {
			order: 90,
			detailsKey: 'rpg.rules.behavior',
		},
		guildOnly: true,
		handler: './handlers/rules',
	},
];

module.exports = { COMMAND_METADATA };
