const GENERATOR_SCHEMA_VERSION = 4;
const GENERATOR_ID_PATTERN = /^[a-z0-9]+(?:_[a-z0-9]+)*$/;
const GENERATOR_VISIBILITIES = new Set(['internal', 'public']);
const MAX_ENTRY_TEXT_LENGTH = 4_096;
const MAX_ENTRY_NAME_LENGTH = 256;
const MAX_FIELD_VALUE_LENGTH = 1_024;
const MAX_MODIFIER_SOURCES = 25;
const CREATURE_ROUTER_ID = 'creature';
module.exports = {
	CREATURE_ROUTER_ID,
	GENERATOR_ID_PATTERN,
	GENERATOR_SCHEMA_VERSION,
	GENERATOR_VISIBILITIES,
	MAX_ENTRY_NAME_LENGTH,
	MAX_ENTRY_TEXT_LENGTH,
	MAX_FIELD_VALUE_LENGTH,
	MAX_MODIFIER_SOURCES,
};
